//permission
export const GENERATE_ROUTES = 'GENERATE_ROUTES';

export const SET_ROUTES = 'SET_ROUTES';

// account
export const USER_LOGIN = 'USER_LOGIN';

export const GET_USER_AUTH = 'GET_USER_AUTH'; 

export const SET_USER = 'SET_USER';

export const USER_LOGOUT = 'USER_LOGOUT';

export const GET_ALL_USERS = 'GET_ALL_USERS';

export const SET_ALL_USERS = 'SET_ALL_USERS';

export const ADD_OR_MODIFY_ONE_USER = 'ADD_OR_MODIFY_ONE_USER';

export const DEL_ONE_USER = 'DEL_ONE_USER';

export const QUERY_ONE_USER = 'QUERY_ONE_USER';

export const GET_USER_METIER = 'GET_USER_METIER'

export const SET_USER_METIER = 'SET_USER_METIER'; 

export const SET_METIER_FOR_USER = 'SET_METIER_FOR_USER';


// role 
export const GET_ALL_ROLES = 'GET_ALL_ROLES';

export const SET_ALL_ROLES = 'SET_ALL_ROLES';

export const ADD_ONE_ROLE = 'ADD_ONE_ROLE';

export const DEL_ONE_ROLE = 'DEL_ONE_ROLE';

export const MODIFY_ONE_ROLE = 'MODIFY_ONE_ROLE';


//permit
export const GET_ALL_PERMITS = 'GET_ALL_PERMITS';

export const SET_ALL_PERMITS = 'SET_ALL_PERMITS';

export const SET_SELECTED_PERMITS = 'SET_SELECTED_PERMITS';

export const GET_ROLE_PERMIT = 'GET_ROLE_PERMIT';

export const SET_ROLE_PERMIT = 'SET_ROLE_PERMIT';


//machine
export const ADD_MACHINE = 'ADD_MACHINE';

export const GET_ALL_MACHINES = 'GET_ALL_MACHINES';

export const SET_ALL_MACHINES = 'SET_ALL_MACHINES';

export const SET_CUR_MACHINE = 'SET_CUR_MACHINE';

export const MACHINE_CLOSE = 'MACHINE_CLOSE';

export const MACHINE_STATE = 'MACHINE_STATE';

export const MACHINE_RECHARGE = 'MACHINE_RECHARGE';

export const MACHINE_START = 'MACHINE_START';

export const MACHINE_STOP = 'MACHINE_STOP';

export const MACHINE_REPORT_FAULT = 'MACHINE_REPORT_FAULT';

export const MACHINE_REPORT_STATUS = 'MACHINE_REPORT_STATUS';

export const MACHINE_SET_HEART = 'MACHINE_SET_HEART';

export const MACHINE_SET_PERIOD = 'MACHINE_SET_PERIOD';

export const MACHINE_SET_SECTION = 'MACHINE_SET_SECTION';


//mission
export const GET_AUTO_MISSIONS = 'GET_AUTO_MISSIONS';

export const SET_AUTO_MISSIONS = 'SET_AUTO_MISSIONS';

export const BATCH_AUTO_MISSIONS = 'BATCH_AUTO_MISSIONS';

export const ADD_AUTO_MISSION = 'ADD_AUTO_MISSION';

export const DEL_AUTO_MISSION = 'DEL_AUTO_MISSION';


//sensor
export const GET_ALL_SENSORS = 'GET_ALL_SENSORS';

export const SET_ALL_SENSORS = 'SET_ALL_SENSORS';

export const GET_SENSOR_FROM_MACHINE = 'GET_SENSOR_FROM_MACHINE';

export const CUR_MACHINE_SENSORIDS = 'CUR_MACHINE_SENSORIDS';

export const CUR_MACHINE_SENSOR_VALUE = 'CUR_MACHINE_SENSOR_VALUE';

export const SET_SENSORS_FOR_MACHINE = 'SET_SENSORS_FOR_MACHINE';

export const SET_SENSOR_VALUE = 'SET_SENSOR_VALUE';

export const GET_CURVE_GRAPH = 'GET_CURVE_GRAPH';

export const SET_CURVE_GRAPH = 'SET_CURVE_GRAPH'


//notifaction
export const SET_STATICTIS = 'SET_STATICTIS';

export const SET_WARNING = 'SET_WARNING'; 


//maintain
export const GET_FAULT_TYPE = 'GET_FAULT_TYPE';

export const SET_FAULT_TYPE = 'SET_FAULT_TYPE'; 

export const GET_MAINTAIN_LIST = 'GET_MAINTAIN_LIST'; 

export const SET_MAINTAIN_LIST = 'SET_MAINTAIN_LIST'; 

export const CUR_MAINTAIN_ORDER = 'CUR_MAINTAIN_ORDER';

export const CREATE_WORK_ORDER = 'CREATE_WORK_ORDER';

export const START_REPAIR = 'START_REPAIR';

export const RESOLVE_REPAIR = 'RESOLVE_REPAIR';

export const UNRESOLVE_REPAIR = 'UNRESOLVE_REPAIR';

//chat
export const CHAT_DIALOG_VISIBLE = 'CHAT_DIALOG_VISIBLE'

export const IS_CALL = 'IS_CALL'